// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfKBwMmyyyBN_uQIuI96M9IQ_mAcAG3Ag',
    appId: '1:907625414351:web:bae4dce884e9ba8ba481ba',
    messagingSenderId: '907625414351',
    projectId: 'woodie-2fc15',
    authDomain: 'woodie-2fc15.firebaseapp.com',
    storageBucket: 'woodie-2fc15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzWYKsiZsZIYz0LIDGL6oieMWQAxHBx2Q',
    appId: '1:907625414351:android:8d1a2fcb5795bf32a481ba',
    messagingSenderId: '907625414351',
    projectId: 'woodie-2fc15',
    storageBucket: 'woodie-2fc15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC8z-RIgkaNFXM8IlrzdakiBDSlfAWcx0',
    appId: '1:907625414351:ios:eb8c0e98578a7034a481ba',
    messagingSenderId: '907625414351',
    projectId: 'woodie-2fc15',
    storageBucket: 'woodie-2fc15.appspot.com',
    iosClientId: '907625414351-du8pfekkgpqceu8nltdrp0kt0i29ltsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.woodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC8z-RIgkaNFXM8IlrzdakiBDSlfAWcx0',
    appId: '1:907625414351:ios:a44f47a7b968bf7ea481ba',
    messagingSenderId: '907625414351',
    projectId: 'woodie-2fc15',
    storageBucket: 'woodie-2fc15.appspot.com',
    iosClientId: '907625414351-u3vbc8gefp72elpgjpa97kiaeqciua2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.woodie.RunnerTests',
  );
}
